package com.proint1.udea.microcurriculo;

import com.proint1.udea.administracion.TbAdmCurso;

// default package
// Generated 18/05/2014 06:35:43 PM by Hibernate Tools 3.4.0.CR1

/**
 * TbMicCursosxpensum generated by hbm2java
 */
public class TbMicCursosxpensum implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long nbCpeIdn;
	private TbMicVersionpensum tbMicVersionpensum;
	private TbAdmCurso tbAdmCurso;

	public TbMicCursosxpensum() {
	}

	public TbMicCursosxpensum(long nbCpeIdn,
			TbMicVersionpensum tbMicVersionpensum, TbAdmCurso tbAdmCurso) {
		this.nbCpeIdn = nbCpeIdn;
		this.tbMicVersionpensum = tbMicVersionpensum;
		this.tbAdmCurso = tbAdmCurso;
	}

	public long getNbCpeIdn() {
		return this.nbCpeIdn;
	}

	public void setNbCpeIdn(long nbCpeIdn) {
		this.nbCpeIdn = nbCpeIdn;
	}

	public TbMicVersionpensum getTbMicVersionpensum() {
		return this.tbMicVersionpensum;
	}

	public void setTbMicVersionpensum(TbMicVersionpensum tbMicVersionpensum) {
		this.tbMicVersionpensum = tbMicVersionpensum;
	}

	public TbAdmCurso getTbAdmCurso() {
		return this.tbAdmCurso;
	}

	public void setTbAdmCurso(TbAdmCurso tbAdmCurso) {
		this.tbAdmCurso = tbAdmCurso;
	}

}
