package com.proint1.udea.administracion;

// default package
// Generated 18/05/2014 06:35:43 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmRol generated by hbm2java
 */
public class TbAdmRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal nbRolIdn;
	private String vrRolNombre;
	private Set tbAdmPermisosxrols = new HashSet(0);
	private Set tbAdmUsuarioxrols = new HashSet(0);

	public TbAdmRol() {
	}

	public TbAdmRol(BigDecimal nbRolIdn, String vrRolNombre) {
		this.nbRolIdn = nbRolIdn;
		this.vrRolNombre = vrRolNombre;
	}

	public TbAdmRol(BigDecimal nbRolIdn, String vrRolNombre,
			Set tbAdmPermisosxrols, Set tbAdmUsuarioxrols) {
		this.nbRolIdn = nbRolIdn;
		this.vrRolNombre = vrRolNombre;
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
	}

	public BigDecimal getNbRolIdn() {
		return this.nbRolIdn;
	}

	public void setNbRolIdn(BigDecimal nbRolIdn) {
		this.nbRolIdn = nbRolIdn;
	}

	public String getVrRolNombre() {
		return this.vrRolNombre;
	}

	public void setVrRolNombre(String vrRolNombre) {
		this.vrRolNombre = vrRolNombre;
	}

	public Set getTbAdmPermisosxrols() {
		return this.tbAdmPermisosxrols;
	}

	public void setTbAdmPermisosxrols(Set tbAdmPermisosxrols) {
		this.tbAdmPermisosxrols = tbAdmPermisosxrols;
	}

	public Set getTbAdmUsuarioxrols() {
		return this.tbAdmUsuarioxrols;
	}

	public void setTbAdmUsuarioxrols(Set tbAdmUsuarioxrols) {
		this.tbAdmUsuarioxrols = tbAdmUsuarioxrols;
	}

}
