package com.proint1.udea.administracion;

// default package
// Generated 18/05/2014 06:35:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbAdmPersona generated by hbm2java
 */
public class TbAdmPersona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long nbIdn;
	private TbAdmTipoidentificacion tbAdmTipoidentificacion;
	private String vrAdtusuario;
	private Date dtAdtfecha;
	private String vrNombres;
	private String vrApellidos;
	private String vrIdentificacion;
	private String vrDireccion;
	private String vrTelefono;
	private String vrEmail;
	private Set tbAdmDocentes = new HashSet(0);
	private Set tbPrdAutors = new HashSet(0);
	private Set tbPrdGrupoinvestigacions = new HashSet(0);
	private Set tbAdmEstudiantes = new HashSet(0);
	private Set tbPrdMiembrosxgrupos = new HashSet(0);
	private Set tbAdmUsuarios = new HashSet(0);

	public TbAdmPersona() {
	}

	public TbAdmPersona(long nbIdn,
			TbAdmTipoidentificacion tbAdmTipoidentificacion,
			String vrAdtusuario, Date dtAdtfecha, String vrNombres,
			String vrApellidos, String vrIdentificacion) {
		this.nbIdn = nbIdn;
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
		this.vrIdentificacion = vrIdentificacion;
	}

	public TbAdmPersona(long nbIdn,
			TbAdmTipoidentificacion tbAdmTipoidentificacion,
			String vrAdtusuario, Date dtAdtfecha, String vrNombres,
			String vrApellidos, String vrIdentificacion, String vrDireccion,
			String vrTelefono, String vrEmail, Set tbAdmDocentes,
			Set tbPrdAutors, Set tbPrdGrupoinvestigacions,
			Set tbAdmEstudiantes, Set tbPrdMiembrosxgrupos, Set tbAdmUsuarios) {
		this.nbIdn = nbIdn;
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
		this.vrAdtusuario = vrAdtusuario;
		this.dtAdtfecha = dtAdtfecha;
		this.vrNombres = vrNombres;
		this.vrApellidos = vrApellidos;
		this.vrIdentificacion = vrIdentificacion;
		this.vrDireccion = vrDireccion;
		this.vrTelefono = vrTelefono;
		this.vrEmail = vrEmail;
		this.tbAdmDocentes = tbAdmDocentes;
		this.tbPrdAutors = tbPrdAutors;
		this.tbPrdGrupoinvestigacions = tbPrdGrupoinvestigacions;
		this.tbAdmEstudiantes = tbAdmEstudiantes;
		this.tbPrdMiembrosxgrupos = tbPrdMiembrosxgrupos;
		this.tbAdmUsuarios = tbAdmUsuarios;
	}

	public long getNbIdn() {
		return this.nbIdn;
	}

	public void setNbIdn(long nbIdn) {
		this.nbIdn = nbIdn;
	}

	public TbAdmTipoidentificacion getTbAdmTipoidentificacion() {
		return this.tbAdmTipoidentificacion;
	}

	public void setTbAdmTipoidentificacion(
			TbAdmTipoidentificacion tbAdmTipoidentificacion) {
		this.tbAdmTipoidentificacion = tbAdmTipoidentificacion;
	}

	public String getVrAdtusuario() {
		return this.vrAdtusuario;
	}

	public void setVrAdtusuario(String vrAdtusuario) {
		this.vrAdtusuario = vrAdtusuario;
	}

	public Date getDtAdtfecha() {
		return this.dtAdtfecha;
	}

	public void setDtAdtfecha(Date dtAdtfecha) {
		this.dtAdtfecha = dtAdtfecha;
	}

	public String getVrNombres() {
		return this.vrNombres;
	}

	public void setVrNombres(String vrNombres) {
		this.vrNombres = vrNombres;
	}

	public String getVrApellidos() {
		return this.vrApellidos;
	}

	public void setVrApellidos(String vrApellidos) {
		this.vrApellidos = vrApellidos;
	}

	public String getVrIdentificacion() {
		return this.vrIdentificacion;
	}

	public void setVrIdentificacion(String vrIdentificacion) {
		this.vrIdentificacion = vrIdentificacion;
	}

	public String getVrDireccion() {
		return this.vrDireccion;
	}

	public void setVrDireccion(String vrDireccion) {
		this.vrDireccion = vrDireccion;
	}

	public String getVrTelefono() {
		return this.vrTelefono;
	}

	public void setVrTelefono(String vrTelefono) {
		this.vrTelefono = vrTelefono;
	}

	public String getVrEmail() {
		return this.vrEmail;
	}

	public void setVrEmail(String vrEmail) {
		this.vrEmail = vrEmail;
	}

	public Set getTbAdmDocentes() {
		return this.tbAdmDocentes;
	}

	public void setTbAdmDocentes(Set tbAdmDocentes) {
		this.tbAdmDocentes = tbAdmDocentes;
	}

	public Set getTbPrdAutors() {
		return this.tbPrdAutors;
	}

	public void setTbPrdAutors(Set tbPrdAutors) {
		this.tbPrdAutors = tbPrdAutors;
	}

	public Set getTbPrdGrupoinvestigacions() {
		return this.tbPrdGrupoinvestigacions;
	}

	public void setTbPrdGrupoinvestigacions(Set tbPrdGrupoinvestigacions) {
		this.tbPrdGrupoinvestigacions = tbPrdGrupoinvestigacions;
	}

	public Set getTbAdmEstudiantes() {
		return this.tbAdmEstudiantes;
	}

	public void setTbAdmEstudiantes(Set tbAdmEstudiantes) {
		this.tbAdmEstudiantes = tbAdmEstudiantes;
	}

	public Set getTbPrdMiembrosxgrupos() {
		return this.tbPrdMiembrosxgrupos;
	}

	public void setTbPrdMiembrosxgrupos(Set tbPrdMiembrosxgrupos) {
		this.tbPrdMiembrosxgrupos = tbPrdMiembrosxgrupos;
	}

	public Set getTbAdmUsuarios() {
		return this.tbAdmUsuarios;
	}

	public void setTbAdmUsuarios(Set tbAdmUsuarios) {
		this.tbAdmUsuarios = tbAdmUsuarios;
	}

}
